---
esphome:
  name: $name
  friendly_name: $friendly_name
  project:
    name: kellertk.esphome-diy-gdo
    version: 0.1.0
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 800
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

i2c:
  - id: bus_a
    sda: $sda
    scl: $scl
    scan: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"

preferences:
  flash_write_interval: 48h

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    id: restart_button
    entity_category: config

light:
  - platform: status_led
    id: led
    name: Status LED
    internal: true
    pin:
      number: $status_led
      inverted: $status_led_inverted
      ignore_strapping_warning: true

ota:
  - platform: esphome
